-- Таблица транспортных средств
CREATE TABLE vehicles (
    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_type VARCHAR2(50),
    brand VARCHAR2(100),
    manufacture_year NUMBER(4),
    commission_date DATE,
    decommission_date DATE,
    capacity NUMBER,
    payload_capacity NUMBER,
    usage_intensity NUMBER,
    mileage NUMBER,
    repair_count NUMBER,
    repair_cost_total NUMBER(12, 2)
);

-- Таблица водителей
CREATE TABLE drivers (
    driver_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(200),
    experience_years NUMBER,
    license_category VARCHAR2(10)
);

-- Таблица закрепления водителей за транспортом
CREATE TABLE vehicle_driver_assignments (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id NUMBER,
    vehicle_id NUMBER,
    assignment_start_date DATE,
    assignment_end_date DATE,
    CONSTRAINT fk_vda_driver FOREIGN KEY (driver_id) REFERENCES 
drivers(driver_id),
    CONSTRAINT fk_vda_vehicle FOREIGN KEY (vehicle_id) REFERENCES 
vehicles(vehicle_id)
);

-- Таблица маршрутов
CREATE TABLE routes (
    route_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route_number VARCHAR2(50),
    description VARCHAR2(500),
    passenger_count NUMBER
);

-- Таблица закрепления транспорта за маршрутами
CREATE TABLE vehicle_route_assignments (
    assignment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER,
    route_id NUMBER,
    assignment_start_date DATE,
    assignment_end_date DATE,
    CONSTRAINT fk_vra_vehicle FOREIGN KEY (vehicle_id) REFERENCES 
vehicles(vehicle_id),
    CONSTRAINT fk_vra_route FOREIGN KEY (route_id) REFERENCES routes(route_id)
);

-- Таблица обслуживающего персонала
CREATE TABLE maintenance_staff (
    staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(200),
    position VARCHAR2(100),
    team_id NUMBER
);

-- Таблица бригад
CREATE TABLE teams (
    team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_name VARCHAR2(200),
    foreman_id NUMBER,
    CONSTRAINT fk_teams_foreman FOREIGN KEY (foreman_id) REFERENCES 
maintenance_staff(staff_id)
);

-- Добавляем внешний ключ для maintenance_staff после создания teams (из-за взаимной зависимости)
ALTER TABLE maintenance_staff
ADD CONSTRAINT fk_staff_team FOREIGN KEY (team_id) REFERENCES teams(team_id);

-- Таблица цехов и объектов гаражного хозяйства
CREATE TABLE workshops (
    workshop_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workshop_name VARCHAR2(200),
    workshop_type VARCHAR2(100),
    address VARCHAR2(300),
    vehicle_type VARCHAR2(50)
);

-- Таблица начальников участков/цехов
CREATE TABLE workshop_managers (
    manager_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(200),
    position VARCHAR2(100),
    workshop_id NUMBER,
    CONSTRAINT fk_manager_workshop FOREIGN KEY (workshop_id) REFERENCES 
workshops(workshop_id)
);

-- Таблица ремонтов
CREATE TABLE repairs (
    repair_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vehicle_id NUMBER,
    team_id NUMBER,
    repair_date DATE,
    work_volume NUMBER,
    repair_cost NUMBER(12, 2),
    replaced_parts_count NUMBER,
    CONSTRAINT fk_repairs_vehicle FOREIGN KEY (vehicle_id) REFERENCES 
vehicles(vehicle_id),
    CONSTRAINT fk_repairs_team FOREIGN KEY (team_id) REFERENCES teams(team_id)
);

-- Таблица узлов и агрегатов
CREATE TABLE parts (
    part_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_name VARCHAR2(200)
);

-- Таблица замены узлов в рамках ремонта
CREATE TABLE repair_part_replacements (
    replacement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repair_id NUMBER,
    part_id NUMBER,
    status VARCHAR2(50),
    CONSTRAINT fk_rpr_repair FOREIGN KEY (repair_id) REFERENCES 
repairs(repair_id),
    CONSTRAINT fk_rpr_part FOREIGN KEY (part_id) REFERENCES parts(part_id)
);

CREATE TABLE freight_transportation(
fe_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
vehicle_id NUMBER,
date_of_transportation DATE
);
